exp_path: "/home/rdaneel/PBS_results/"
ins_num: 25
time_limit: 60
time_gap: 10

figure_width: 10
figure_height: 10
set_title: true
set_legend: true
marker_size: 25
line_width: 4.0
marker_width: 4.0
text_size: 27

set_shift: true
plot_ci: false
plot_std: false

maps:
  # - name: "random-32-32-20"
  #   label: Random
  #   scens:
  #     - random
  #   num_of_agents:
  #     - 200
  #     - 250
  #     - 300
  #     - 350
  #     - 400

  # - name: "maze-32-32-2"
  #   label: Maze
  #   scens:
  #     - random
  #   num_of_agents:
  #     - 100
  #     - 150
  #     - 200
  #     - 250
  #     - 300

  # - name: "room-32-32-4"
  #   label: Room
  #   scens:
  #     - random
  #   num_of_agents:
  #     - 100
  #     - 150
  #     - 200
  #     - 250
  #     - 300

  # - name: "warehouse-10-20-10-2-1"
  #   label: Warehouse(M)
  #   scens:
  #     - random
  #   num_of_agents:
  #     - 200
  #     - 400
  #     - 600
  #     - 800
  #     - 1000

  # - name: "warehouse-20-40-10-2-1"
  #   label: Warehouse(L)
  #   scens:
  #     - random
  #   num_of_agents:
  #     - 200
  #     - 400
  #     - 600
  #     - 800
  #     - 1000

  - name: "den520d"
    label: Den520d
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

solvers:
  - name: "PP-OPT"
    label: "PP*"
    color: "skyblue"
    marker: "o"
    markerfacecolor: "skyblue"

  - name: "PP"
    label: "PP"
    color: "deepskyblue"
    marker: "o"

  - name: "PP-OPT-LH"
    label: "PP*(LH)"
    marker: "P"
    color: "gray"
    markerfacecolor: "gray"

  - name: "PP-LH"
    label: "PP(LH)"
    color: "dimgray"
    marker: "P"

  - name: "PP-OPT-SH"
    label: "PP*(SH)"
    color: "limegreen"
    marker: "s"
    markerfacecolor: "limegreen"

  - name: "PP-SH"
    label: "PP(SH)"
    color: "green"
    marker: "s"