exp_path: "/home/rdaneel/PBS_results/"
ins_num: 25
time_limit: 60
time_gap: 15

figure_width: 10
figure_height: 10
set_title: true
set_legend: true
marker_size: 25
line_width: 4.0
marker_width: 4.0
text_size: 40

set_shift: 0
plot_ci: false
plot_std: false

maps:
  - name: "random-32-32-20"
    label: Random
    scens:
      - random
    num_of_agents:
      - 200
      - 250
      - 300
      - 350
      - 400

  - name: "maze-32-32-2"
    label: Maze
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "room-32-32-4"
    label: Room
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "warehouse-10-20-10-2-1"
    label: Warehouse(M)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "warehouse-20-40-10-2-1"
    label: Warehouse(L)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "den520d"
    label: Den520d
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

solvers:
  # - name: "PP-OPT"
  #   label: "PP*"
  #   color: "deepskyblue"
  #   marker: "o"
  #   markerfacecolor: "deepskyblue"

  # - name: "PP"
  #   label: "PP"
  #   color: "deepskyblue"
  #   marker: "o"

  # - name: "PP-OPT-LH"
  #   label: "PP*(LH)"
  #   marker: "P"
  #   color: "gray"
  #   markerfacecolor: "gray"

  - name: "PP-LH"
    label: "PP(LH)"
    color: "dimgray"
    marker: "P"

  # - name: "PP-OPT-SH"
  #   label: "PP*(SH)"
  #   color: "limegreen"
  #   marker: "s"
  #   markerfacecolor: "limegreen"

  # - name: "PP-SH"
  #   label: "PP(SH)"
  #   color: "green"
  #   marker: "s"

  - name: "PBS-OPT"
    label: "PBS*"
    color: "orange"
    marker: "d"
    markerfacecolor: "orange"

  # - name: "PBS"
  #   label: "PBS"
  #   color: "darkorange"
  #   marker: "d"

  # - name: "PBS-OPT-greedy"
  #   label: "GPBS*"
  #   marker: "H"
  #   color: "violet"
  #   markerfacecolor: "violet"

  - name: "PBS-greedy"
    label: "GPBS"
    color: "darkviolet"
    marker: "H"

  - name: "PBS2-LH-PE-TR"
    label: "IPBS(PE,TR)"
    color: "green"
    marker: "s"
  
  # - name: "PBS2-LH-PE-IC1"
  #   label: "IPBS(PE,IC)"
  #   color: "gold"
  #   marker: "D"

  - name: "PBS2-LH-PE-TR-IC1-RR50"
    label: "IPBS(PE,TR,IC,RR)"
    color: "red"
    marker: "^"